- name: Upload screenshots
  uses: actions/upload-artifact@v3
  with:
    name: screenshots
    path: cypress/screenshots

- name: Upload videos
  uses: actions/upload-artifact@v3
  with:
    name: videos
    path: cypress/videos